#!/usr/bin/env bash
# Install and configure HAproxy on my lb-01 server.
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  mark-alx-frontend
        bind *:80
        mode http
        default_backend mark-alx-backend
backend mark-alx-backend
        balance roundrobin
        server 479-web-01 34.73.183.163:80 check
        server 479-web-02 34.231.247.198:80 check
"
 echo "$server_config" >> /etc/haproxy/haproxy.cfg

 # enable haproxy to be started by init script

 echo "ENABLED=1" >> /etc/default/haproxy

 sudo service haproxy restart
