#!/usr/bin/env bash
#Install load balancer

sudo apt update
sudo apt-get install -y haproxy=1.6.\*
setup="
frontend firstbalance
    bind *:80
mode http
default_backend webservers
backend webservers
balance roundrobin
server 479-web-01 34.73.183.163 check
server 479-web-02 34.231.247.198 check
"
echo "$setup" >> /etc/haproxy/haproxy.cfg
echo "ENABLED=1" >> /etc/default/haproxy
service haproxy start
